/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as BatchesIndexRouteImport } from './routes/batches.index'
import { Route as ScanIdRouteImport } from './routes/scan.$id'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as PageIdRouteImport } from './routes/page.$id'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as ApiSeoSiteAuditRouteImport } from './routes/api.seo-site-audit'
import { Route as ApiSeoScanUrlsRouteImport } from './routes/api.seo-scan-urls'
import { Route as ApiSeoAuditRouteImport } from './routes/api.seo-audit'
import { Route as ApiScanStartRouteImport } from './routes/api.scan-start'
import { Route as ApiBatchesRunRouteImport } from './routes/api.batches.run'
import { Route as ApiPublicHooksBatchCronRouteImport } from './routes/api.public.hooks.batch-cron'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIdRoute = ScanIdRouteImport.update({
  id: '/scan/$id',
  path: '/scan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PageIdRoute = PageIdRouteImport.update({
  id: '/page/$id',
  path: '/page/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoSiteAuditRoute = ApiSeoSiteAuditRouteImport.update({
  id: '/api/seo-site-audit',
  path: '/api/seo-site-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoScanUrlsRoute = ApiSeoScanUrlsRouteImport.update({
  id: '/api/seo-scan-urls',
  path: '/api/seo-scan-urls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoAuditRoute = ApiSeoAuditRouteImport.update({
  id: '/api/seo-audit',
  path: '/api/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanStartRoute = ApiScanStartRouteImport.update({
  id: '/api/scan-start',
  path: '/api/scan-start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBatchesRunRoute = ApiBatchesRunRouteImport.update({
  id: '/api/batches/run',
  path: '/api/batches/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBatchCronRoute = ApiPublicHooksBatchCronRouteImport.update({
  id: '/api/public/hooks/batch-cron',
  path: '/api/public/hooks/batch-cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/api/scan-start': typeof ApiScanStartRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/api/seo-scan-urls': typeof ApiSeoScanUrlsRoute
  '/api/seo-site-audit': typeof ApiSeoSiteAuditRoute
  '/clients/$id': typeof ClientsIdRoute
  '/page/$id': typeof PageIdRoute
  '/report/$id': typeof ReportIdRoute
  '/scan/$id': typeof ScanIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/api/batches/run': typeof ApiBatchesRunRoute
  '/api/public/hooks/batch-cron': typeof ApiPublicHooksBatchCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/api/scan-start': typeof ApiScanStartRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/api/seo-scan-urls': typeof ApiSeoScanUrlsRoute
  '/api/seo-site-audit': typeof ApiSeoSiteAuditRoute
  '/clients/$id': typeof ClientsIdRoute
  '/page/$id': typeof PageIdRoute
  '/report/$id': typeof ReportIdRoute
  '/scan/$id': typeof ScanIdRoute
  '/batches': typeof BatchesIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/api/batches/run': typeof ApiBatchesRunRoute
  '/api/public/hooks/batch-cron': typeof ApiPublicHooksBatchCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/api/scan-start': typeof ApiScanStartRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/api/seo-scan-urls': typeof ApiSeoScanUrlsRoute
  '/api/seo-site-audit': typeof ApiSeoSiteAuditRoute
  '/clients/$id': typeof ClientsIdRoute
  '/page/$id': typeof PageIdRoute
  '/report/$id': typeof ReportIdRoute
  '/scan/$id': typeof ScanIdRoute
  '/batches/': typeof BatchesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/api/batches/run': typeof ApiBatchesRunRoute
  '/api/public/hooks/batch-cron': typeof ApiPublicHooksBatchCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/api/scan-start'
    | '/api/seo-audit'
    | '/api/seo-scan-urls'
    | '/api/seo-site-audit'
    | '/clients/$id'
    | '/page/$id'
    | '/report/$id'
    | '/scan/$id'
    | '/batches/'
    | '/clients/'
    | '/api/batches/run'
    | '/api/public/hooks/batch-cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/api/scan-start'
    | '/api/seo-audit'
    | '/api/seo-scan-urls'
    | '/api/seo-site-audit'
    | '/clients/$id'
    | '/page/$id'
    | '/report/$id'
    | '/scan/$id'
    | '/batches'
    | '/clients'
    | '/api/batches/run'
    | '/api/public/hooks/batch-cron'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/history'
    | '/api/scan-start'
    | '/api/seo-audit'
    | '/api/seo-scan-urls'
    | '/api/seo-site-audit'
    | '/clients/$id'
    | '/page/$id'
    | '/report/$id'
    | '/scan/$id'
    | '/batches/'
    | '/clients/'
    | '/api/batches/run'
    | '/api/public/hooks/batch-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  ApiScanStartRoute: typeof ApiScanStartRoute
  ApiSeoAuditRoute: typeof ApiSeoAuditRoute
  ApiSeoScanUrlsRoute: typeof ApiSeoScanUrlsRoute
  ApiSeoSiteAuditRoute: typeof ApiSeoSiteAuditRoute
  ClientsIdRoute: typeof ClientsIdRoute
  PageIdRoute: typeof PageIdRoute
  ReportIdRoute: typeof ReportIdRoute
  ScanIdRoute: typeof ScanIdRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  ApiBatchesRunRoute: typeof ApiBatchesRunRoute
  ApiPublicHooksBatchCronRoute: typeof ApiPublicHooksBatchCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/': {
      id: '/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$id': {
      id: '/scan/$id'
      path: '/scan/$id'
      fullPath: '/scan/$id'
      preLoaderRoute: typeof ScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/$id': {
      id: '/page/$id'
      path: '/page/$id'
      fullPath: '/page/$id'
      preLoaderRoute: typeof PageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo-site-audit': {
      id: '/api/seo-site-audit'
      path: '/api/seo-site-audit'
      fullPath: '/api/seo-site-audit'
      preLoaderRoute: typeof ApiSeoSiteAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo-scan-urls': {
      id: '/api/seo-scan-urls'
      path: '/api/seo-scan-urls'
      fullPath: '/api/seo-scan-urls'
      preLoaderRoute: typeof ApiSeoScanUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo-audit': {
      id: '/api/seo-audit'
      path: '/api/seo-audit'
      fullPath: '/api/seo-audit'
      preLoaderRoute: typeof ApiSeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan-start': {
      id: '/api/scan-start'
      path: '/api/scan-start'
      fullPath: '/api/scan-start'
      preLoaderRoute: typeof ApiScanStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/batches/run': {
      id: '/api/batches/run'
      path: '/api/batches/run'
      fullPath: '/api/batches/run'
      preLoaderRoute: typeof ApiBatchesRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/batch-cron': {
      id: '/api/public/hooks/batch-cron'
      path: '/api/public/hooks/batch-cron'
      fullPath: '/api/public/hooks/batch-cron'
      preLoaderRoute: typeof ApiPublicHooksBatchCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  ApiScanStartRoute: ApiScanStartRoute,
  ApiSeoAuditRoute: ApiSeoAuditRoute,
  ApiSeoScanUrlsRoute: ApiSeoScanUrlsRoute,
  ApiSeoSiteAuditRoute: ApiSeoSiteAuditRoute,
  ClientsIdRoute: ClientsIdRoute,
  PageIdRoute: PageIdRoute,
  ReportIdRoute: ReportIdRoute,
  ScanIdRoute: ScanIdRoute,
  BatchesIndexRoute: BatchesIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  ApiBatchesRunRoute: ApiBatchesRunRoute,
  ApiPublicHooksBatchCronRoute: ApiPublicHooksBatchCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
