/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSeoSiteAuditRouteImport } from './routes/api.seo-site-audit'
import { Route as ApiSeoAuditRouteImport } from './routes/api.seo-audit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoSiteAuditRoute = ApiSeoSiteAuditRouteImport.update({
  id: '/api/seo-site-audit',
  path: '/api/seo-site-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoAuditRoute = ApiSeoAuditRouteImport.update({
  id: '/api/seo-audit',
  path: '/api/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/api/seo-site-audit': typeof ApiSeoSiteAuditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/api/seo-site-audit': typeof ApiSeoSiteAuditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/api/seo-site-audit': typeof ApiSeoSiteAuditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/seo-audit' | '/api/seo-site-audit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/seo-audit' | '/api/seo-site-audit'
  id: '__root__' | '/' | '/api/seo-audit' | '/api/seo-site-audit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSeoAuditRoute: typeof ApiSeoAuditRoute
  ApiSeoSiteAuditRoute: typeof ApiSeoSiteAuditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo-site-audit': {
      id: '/api/seo-site-audit'
      path: '/api/seo-site-audit'
      fullPath: '/api/seo-site-audit'
      preLoaderRoute: typeof ApiSeoSiteAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo-audit': {
      id: '/api/seo-audit'
      path: '/api/seo-audit'
      fullPath: '/api/seo-audit'
      preLoaderRoute: typeof ApiSeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSeoAuditRoute: ApiSeoAuditRoute,
  ApiSeoSiteAuditRoute: ApiSeoSiteAuditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
