/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanIdRouteImport } from './routes/scan.$id'
import { Route as ApiSeoSiteAuditRouteImport } from './routes/api.seo-site-audit'
import { Route as ApiSeoScanUrlsRouteImport } from './routes/api.seo-scan-urls'
import { Route as ApiSeoAuditRouteImport } from './routes/api.seo-audit'
import { Route as ApiScanStartRouteImport } from './routes/api.scan-start'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIdRoute = ScanIdRouteImport.update({
  id: '/scan/$id',
  path: '/scan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoSiteAuditRoute = ApiSeoSiteAuditRouteImport.update({
  id: '/api/seo-site-audit',
  path: '/api/seo-site-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoScanUrlsRoute = ApiSeoScanUrlsRouteImport.update({
  id: '/api/seo-scan-urls',
  path: '/api/seo-scan-urls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoAuditRoute = ApiSeoAuditRouteImport.update({
  id: '/api/seo-audit',
  path: '/api/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanStartRoute = ApiScanStartRouteImport.update({
  id: '/api/scan-start',
  path: '/api/scan-start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/scan-start': typeof ApiScanStartRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/api/seo-scan-urls': typeof ApiSeoScanUrlsRoute
  '/api/seo-site-audit': typeof ApiSeoSiteAuditRoute
  '/scan/$id': typeof ScanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/scan-start': typeof ApiScanStartRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/api/seo-scan-urls': typeof ApiSeoScanUrlsRoute
  '/api/seo-site-audit': typeof ApiSeoSiteAuditRoute
  '/scan/$id': typeof ScanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/scan-start': typeof ApiScanStartRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/api/seo-scan-urls': typeof ApiSeoScanUrlsRoute
  '/api/seo-site-audit': typeof ApiSeoSiteAuditRoute
  '/scan/$id': typeof ScanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/scan-start'
    | '/api/seo-audit'
    | '/api/seo-scan-urls'
    | '/api/seo-site-audit'
    | '/scan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/scan-start'
    | '/api/seo-audit'
    | '/api/seo-scan-urls'
    | '/api/seo-site-audit'
    | '/scan/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/scan-start'
    | '/api/seo-audit'
    | '/api/seo-scan-urls'
    | '/api/seo-site-audit'
    | '/scan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiScanStartRoute: typeof ApiScanStartRoute
  ApiSeoAuditRoute: typeof ApiSeoAuditRoute
  ApiSeoScanUrlsRoute: typeof ApiSeoScanUrlsRoute
  ApiSeoSiteAuditRoute: typeof ApiSeoSiteAuditRoute
  ScanIdRoute: typeof ScanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$id': {
      id: '/scan/$id'
      path: '/scan/$id'
      fullPath: '/scan/$id'
      preLoaderRoute: typeof ScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo-site-audit': {
      id: '/api/seo-site-audit'
      path: '/api/seo-site-audit'
      fullPath: '/api/seo-site-audit'
      preLoaderRoute: typeof ApiSeoSiteAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo-scan-urls': {
      id: '/api/seo-scan-urls'
      path: '/api/seo-scan-urls'
      fullPath: '/api/seo-scan-urls'
      preLoaderRoute: typeof ApiSeoScanUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo-audit': {
      id: '/api/seo-audit'
      path: '/api/seo-audit'
      fullPath: '/api/seo-audit'
      preLoaderRoute: typeof ApiSeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan-start': {
      id: '/api/scan-start'
      path: '/api/scan-start'
      fullPath: '/api/scan-start'
      preLoaderRoute: typeof ApiScanStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiScanStartRoute: ApiScanStartRoute,
  ApiSeoAuditRoute: ApiSeoAuditRoute,
  ApiSeoScanUrlsRoute: ApiSeoScanUrlsRoute,
  ApiSeoSiteAuditRoute: ApiSeoSiteAuditRoute,
  ScanIdRoute: ScanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
